/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AreaEightFancyBox: typeof import('./src/components/fancybox/AreaEightFancyBox.vue')['default']
    Back: typeof import('./src/components/back/Back.vue')['default']
    EightDot: typeof import('./src/components/eight/EightDot.vue')['default']
    EightLeft: typeof import('./src/components/eight/EightLeft.vue')['default']
    EightList: typeof import('./src/components/eight/EightList.vue')['default']
    EightMask: typeof import('./src/components/eight/EightMask.vue')['default']
    EightTitle: typeof import('./src/components/eight/EightTitle.vue')['default']
    EightTrain: typeof import('./src/components/eight/EightTrain.vue')['default']
    Example: typeof import('./src/components/example/Example.vue')['default']
    FadeDownUp: typeof import('./src/components/transition/FadeDownUp.vue')['default']
    FadeIn: typeof import('./src/components/transition/FadeIn.vue')['default']
    FadeInItem: typeof import('./src/components/transition/FadeInItem.vue')['default']
    FloorPoints: typeof import('./src/components/floorPlan/FloorPoints.vue')['default']
    FullScreen: typeof import('./src/components/fullscreen/FullScreen.vue')['default']
    Glow: typeof import('./src/components/glow/Glow.vue')['default']
    HomeNav: typeof import('./src/components/home/HomeNav.vue')['default']
    LoanForm: typeof import('./src/components/loan/LoanForm.vue')['default']
    LoanResult: typeof import('./src/components/loan/LoanResult.vue')['default']
    MaterialBox: typeof import('./src/components/material/MaterialBox.vue')['default']
    MaterialFancyBox: typeof import('./src/components/fancybox/MaterialFancyBox.vue')['default']
    MaterialKBBox: typeof import('./src/components/material/MaterialKB-Box.vue')['default']
    Nav: typeof import('./src/components/nav/Nav.vue')['default']
    NavChild: typeof import('./src/components/nav/NavChild.vue')['default']
    NormalFancyBox: typeof import('./src/components/fancybox/NormalFancyBox.vue')['default']
    PageFixed: typeof import('./src/components/pageFixed/PageFixed.vue')['default']
    RightToLeft: typeof import('./src/components/transition/RightToLeft.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleDrag: typeof import('./src/components/scaledrag/ScaleDrag.vue')['default']
    ScaleIn: typeof import('./src/components/transition/ScaleIn.vue')['default']
    TransMask: typeof import('./src/components/trans/TransMask.vue')['default']
    WaterProof: typeof import('./src/components/waterProof/WaterProof.vue')['default']
    WaterProofFancyBox: typeof import('./src/components/fancybox/WaterProofFancyBox.vue')['default']
    WindowClose: typeof import('./src/components/close/WindowClose.vue')['default']
  }
}
