/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FadeIn: typeof import('./src/components/transition/FadeIn.vue')['default']
    FadeInItem: typeof import('./src/components/transition/FadeInItem.vue')['default']
    HomeNav: typeof import('./src/components/home/HomeNav.vue')['default']
    Nav: typeof import('./src/components/nav/Nav.vue')['default']
    NavChild: typeof import('./src/components/nav/NavChild.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
